# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'AvaloniaVS.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 7.0'
  inputs:
    version: 7.0.100

- task: DotNetCoreCLI@2
  inputs:
  command: 'restore'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
  command: 'test'

- task: CopyFiles@2
  inputs:
    contents: |
      AvaloniaVS.VS2019AndEarlier\bin\Release\AvaloniaVS.VS2019AndEarlier.vsix
      AvaloniaVS.VS2019AndEarlier\bin\Release\publishManifest.json
      AvaloniaVS.VS2019AndEarlier\bin\Release\overview.md
      AvaloniaVS.VS2022\bin\Release\AvaloniaVS.VS2022.vsix
      AvaloniaVS.VS2022\bin\Release\publishManifest.json
      AvaloniaVS.VS2022\bin\Release\overview.md
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'publish'
  condition: succeeded()
