# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-2022'

variables:
  solution: 'AvaloniaVS.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 8.0'
  inputs:
    version: 8.0.303

- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: 'test'
    projects: '**/CompletionEngineTests.csproj'
    testRunTitle: 'AvaloniaVS Completion Engine Tests'
    arguments: --logger trx

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishTestResults@2
  inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(Build.SourcesDirectory)/**/*.trx'
  condition: not(canceled())

- task: CopyFiles@2
  inputs:
    Contents: |
      AvaloniaVS.VS2022\bin\Release\AvaloniaVS.VS2022.vsix
      AvaloniaVS.VS2022\bin\Release\publishManifest.json
      AvaloniaVS.VS2022\bin\Release\overview.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'publish'
  condition: succeeded()
